name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.0.1
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.0.1
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  provider: ^6.0.4
  google_maps_webservice: ^0.0.20-nullsafety.1
  google_api_headers: ^1.0.0
  tuple: ^2.0.1
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
